"""added file bytes column to resume table

Revision ID: 0707c7aa30d8
Revises: 1d46873aab2a
Create Date: 2022-04-15 17:56:50.289550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0707c7aa30d8'
down_revision = '1d46873aab2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('file', sa.LargeBinary().with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'file')
    # ### end Alembic commands ###
