"""added json column to resume table

Revision ID: 8c91dce7f202
Revises: 3a612287d937
Create Date: 2022-03-11 16:39:46.657292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c91dce7f202'
down_revision = '3a612287d937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'content')
    # ### end Alembic commands ###
