"""Added timestamp for resumetag table

Revision ID: ada556ce4a45
Revises: 1d46873aab2a
Create Date: 2022-05-31 14:57:09.699782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada556ce4a45'
down_revision = '1d46873aab2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_jobs_timestamp'), 'jobs', ['timestamp'], unique=False)
    op.add_column('resumetag', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_resumetag_timestamp'), 'resumetag', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumetag_timestamp'), table_name='resumetag')
    op.drop_column('resumetag', 'timestamp')
    op.drop_index(op.f('ix_jobs_timestamp'), table_name='jobs')
    op.drop_column('jobs', 'timestamp')
    op.drop_column('jobs', 'name')
    # ### end Alembic commands ###
