"""Removed unique constraints

Revision ID: b7601d730b98
Revises: ce42fef19146
Create Date: 2022-06-03 13:21:51.640387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7601d730b98'
down_revision = 'ce42fef19146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('resumetag', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('ix_resumetag_name', table_name='resumetag')
    op.create_index(op.f('ix_resumetag_name'), 'resumetag', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumetag_name'), table_name='resumetag')
    op.create_index('ix_resumetag_name', 'resumetag', ['name'], unique=False)
    op.alter_column('resumetag', 'name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('jobs', 'name',
               existing_type=sa.String(length=256),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
