"""Added name and description columns for resume tags

Revision ID: ce42fef19146
Revises: ada556ce4a45
Create Date: 2022-06-03 10:35:12.846548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce42fef19146'
down_revision = 'ada556ce4a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumetag', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('resumetag', sa.Column('description', sa.Text(), nullable=True))
    op.drop_index('ix_resumetag_tag', table_name='resumetag')
    op.create_index(op.f('ix_resumetag_name'), 'resumetag', ['name'], unique=True)
    op.drop_column('resumetag', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumetag', sa.Column('tag', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_resumetag_name'), table_name='resumetag')
    op.create_index('ix_resumetag_tag', 'resumetag', ['tag'], unique=False)
    op.drop_column('resumetag', 'description')
    op.drop_column('resumetag', 'name')
    # ### end Alembic commands ###
